### ISSUE TITLE
Intentar crear HTML

### ISSUE THREAD

**Issue by mluisdelgado** [alu0100204148/ExamenLDE#11]
Intentar que el parser cree un html con el examen.

**Comment by alu0100204148** [comment]
Creo que eso es bastante simple, hay una función que se llama innerHTML que transforma un string a html dentro  de un elemento. Encontré un ejemplo:

```
var output = document.getElementById("js-output");
var htmlButton = '<a href="#" class="btn" id="button' + index + '">click here please</a>';
output.innerHTML = htmlButton + output.innerHTML;
```

**Comment by alu0100204148** [comment]
No es el mejor ejemplo, pero creo que se entiende.

**Comment by alu0100204148** [comment]
http://www.w3schools.com/jsref/prop_html_innerhtml.asp

**Comment by mluisdelgado** [comment]
El problema no es ese, ya que o bien lo que tu dices o jQuery, el problema sería crearlo en una nueva ventana a modo de ejemplo, y buscar la forma de utilizar el parser para que cree un html y un javascript que comprueben las propias preguntas, y despues de un par de horas trabajando en ello es bastante complicado.

**Comment by mluisdelgado** [comment]
Otra opción sería cargarlo en la misma página, pero me parece poco organizada.

**Comment by alu0100204148** [comment]
Tendrías que tener una pagina ya creada la que le envías el bloque y te lo muestra. Mandandole un json con ajax?

**Comment by mluisdelgado** [comment]
Esa fue la primera solucion en la que pense pero la comunicacion entre páginas es un problemon, con cadenas complejas suele fallar, como dice en este [artículo](http://www.manasinc.com/communicating-between-two-browser-windows-using-jquery-and-custom-events/).

**Comment by mluisdelgado** [comment]
Ultimo problema arreglado gracias a http://stackoverflow.com/questions/30200921/generated-window-with-javascript-on-it-not-working/30201197#30201197
