### ISSUE TITLE
Errores de parser.

### ISSUE THREAD

**Issue by alu0100204148** [alu0100204148/ExamenLDE#12]
Estoy probando el parser, y creando las preguntas ejemplos y da errores con <, >, ?, ¿, parece ser que solo acepta palabras.

SyntaxError: Expected "\"" or [a-zA-Z0-9 ] but "?" found.

**Comment by alu0100204148** [comment]
Tb da error al usar el punto . y debería usar comilla simple '  .

**Comment by mluisdelgado** [comment]
Arreglado.
