### ISSUE TITLE
Pruebas mocha + chai.

### ISSUE THREAD

**Issue by alu0100204148** [alu0100204148/ExamenLDE#2]

**Comment by alu0100204148** [comment]
La estructura básica de las pruebas esta funcionando, queda actualizar las pruebas a unas concretas de este proyecto.

**Comment by mluisdelgado** [comment]
Me encargo, ya que programo el lenguaje.

**Comment by alu0100204148** [comment]
Arreglado el cambio de nombre del fichero pegjs, solo queda modificar pruebas para que representen los últimos cambios realizados en la estructura.

**Comment by mluisdelgado** [comment]
Todo funcionando.
