### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by alu0100204148** [alu0100204148/ExamenLDE#3]

**Comment by alu0100204148** [comment]
Travis funcionando, queda verificar que con los tests finales esté correcto.

**Comment by mluisdelgado** [comment]
Me paso el relevo para la creación de los tests sobre tu platilla.

**Comment by alu0100204148** [comment]
No esta pasando Travis ahora mismo, tan solo por el cambio de las comillas. Ten eso presente.

**Comment by mluisdelgado** [comment]
Todo funcionando.
