### ISSUE TITLE
Código de Examen Pegjs

### ISSUE THREAD

**Issue by alu0100204148** [alu0100204148/ExamenLDE#4]
Como ya hemos comentado los exámenes se definirán de la forma:

TituloExamen,fechaExamen, profesor, asignatura{
    Enunciado de la pregunta1( respuesta1, voF;
                                                 respuesta2, voF;
                                                 respuesta3;voF);
    Enunciado de la pregunta2( respuesta1, voF; respuesta2, voF;respuesta3;voF);
    Enunciado de la pregunta3( respuesta1, voF; respuesta2, voF;respuesta3;voF);
}

Para ello se usara pegjs.

**Comment by mluisdelgado** [comment]
Listo el parser.
