### ISSUE TITLE
Contenido de la página.

### ISSUE THREAD

**Issue by alu0100204148** [alu0100204148/ExamenLDE#5]
La aplicación deberá contener una barra de menú, con enlaces a diferentes paginas. El contenido básico deberá contener almenos una pagina con información de el grupo y componentes, enlace al repositorio git. La pagina principal en la que introducirá el texto, deberá contener un botón para cargar ficheros, botones que carguen ejemplos y un botón que cargue una plantilla para que el usuario sepa como ordenar el texto para crear un examen. Es decir algo del tipo:

TituloExamen,fechaExamen, profesor, asignatura{
Enunciado de la pregunta1[ respuesta1, voF; respuesta2, voF;respuesta3;voF];
Enunciado de la pregunta2[ respuesta1, voF; respuesta2, voF;respuesta3;voF];
Enunciado de la pregunta3[ respuesta1, voF; respuesta2, voF;respuesta3;voF];
}

Donde el usuario pueda substituir.

Intentar usar jade y layouts, http://jade-lang.com/reference/extends/

**Comment by 0100354256** [comment]
Creada plantilla (layout.jade) en adcaa863e223d98975640abd6cd27df73b80e01c.

**Comment by mluisdelgado** [comment]
Añadir mejoras al lenguaje cuando sean aprobadas.

**Comment by 0100354256** [comment]
Creada hoja de estilos scss para la  [plantilla](http://examenlde.herokuapp.com/) en c5357c3ad96b51f90d2f1cefc896a4bd47c48255, a falta de los estilos del contenido.

¿Algún cambio o mejora?

**Comment by alu0100204148** [comment]
En la parte de los tests, la barra se deforma toda aun lado. Y cambiaría el color de las letras a algo un poco mas oscuro.

**Comment by alu0100204148** [comment]
La parte de grammar habría que ponerle otro nombre, algo para definir el uso del LDE. el nombre Grammar no tiene mucho sentido en este proyecto. Dime que nombre le ponemos para establecerlo en el servidor.

**Comment by 0100354256** [comment]
Cierto, hay que adaptar el resto de páginas a la plantilla y estilos. Si quizá se ven poco las letras, las oscureceré un poco.

Lo de grammar, personalmente no lo cambiaría, al fin y al cabo una gramática es un conjunto de reglas que conforman un lenguaje.

**Comment by 0100354256** [comment]
En realidad podemos llamarlo lenguaje también en vez de grammar.
Entonces faltaría establecer dos rutas: /lenguaje y /contributors o /collaborators

**Comment by alu0100204148** [comment]
Añadidos /lenguaje y /contributors.

**Comment by 0100354256** [comment]
Corregido problema con los estilos y plantilla adaptada al resto de páginas: 365a355e0a2fcb9a4f1da0d4af57c38e3d56992f

**Comment by 0100354256** [comment]
Creada la página de los  [colaboradores](http://examenlde.herokuapp.com/contributors): 4c90ba76387bf8ad6129540e5f32530be764eaa0
¿Algo que añadirle?

Falta:
- Estilos del examen generado
- Definir las reglas del lenguaje en la página del lenguaje

**Comment by alu0100204148** [comment]
Ten presente que cambiamos un poco la definición de la estructura del lenguaje, ahora usa comillas simples, por facilitar el uso de comillas dobles dentro de las preguntas al definir código.

'Titulo',01-01-2015,'Profesor','Asignatura'{
  'Pregunta 1' ['Respuesta 1 1', F;  'Respuesta 1 2', V;]
  'Pregunta 2' ['Respuesta 1 2', V;  'Respuesta 2 2', V;]
  'Pregunta 3' ['Respuesta 1 3', V;  'Respuesta 3 2', V;  'Respuesta 3 3', F;]
  'Pregunta 4' ['Respuesta 1 4', V;  'Respuesta 4 2', V;]
};

Se puede ver en la plantilla que se puede cargar en la pagina.

**Comment by 0100354256** [comment]
Actualizada la página del [lenguaje](http://examenlde.herokuapp.com/lenguaje): 0ac43389c3cc3b3e0582e0270569706ca17b0cd7

Falta:
- Estilos del examen generado

**Comment by mluisdelgado** [comment]
Estilos del examen generado acabados, cierra el issue si no vas a cambiar alguna otra cosa.
