### ISSUE TITLE
Necesidad de ampliar el lenguaje.

### ISSUE THREAD

**Issue by mluisdelgado** [alu0100204148/ExamenLDE#8]
Ampliar el lenguaje para la modificación de preguntas en concreto, el borrado de examenes, cambio de orden aleatorio de las preguntas, impresión del examen, generar un PDF, y la modificación de distintos atributos.

**Comment by mluisdelgado** [comment]
Propongo:
NombreExamen.modify(numeroPregunta) => nuevaPregunta
nombreExamen.delete();
nombreExamen.reArrange();
nombreExamen,print();
nombreExamen.getPDF("rutaGuardado");
nombreExamen.set<NombreAtributo>("nuevoValor");

**Comment by mluisdelgado** [comment]
nombreExamen.run();

**Comment by alu0100204148** [comment]
Tal y como yo lo veo, el lenguaje define como se estructura, en este caso, el bloque de datos. El conjunto de métodos que se empleen son irrelevantes. Mañana lo discutimos.

**Comment by mluisdelgado** [comment]
Nuevo issue con nuevas ideas 
[LINK](https://github.com/alu0100204148/ExamenLDE/issues/11)
