### ISSUE TITLE
Subir PEGJS

### ISSUE THREAD

**Issue by mluisdelgado** [alu0100204148/ExamenLDE#9]
Subir PEGJS y reorganizar los ficheros de local.

**Comment by alu0100204148** [comment]
Hay algunos nombres de variables que se heredan de un proyecto anterior, pl0 creo. Asegúrate de poner algo que tenga sentido en este. Por ejemplo LDE.

**Comment by mluisdelgado** [comment]
Si, como dije, reorganizar los ficheros.

**Comment by mluisdelgado** [comment]
Subido y reorganizado.
